language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

env:
  - SECRET_KEY = '&a@9tvuzbasc!l%w3)@jdywh8-q)26wxltybqv#1&)-!&+bo#&'

script:
  - docker-compose run app sh -c "python manage.py test && flake8"